// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package jobs

import (
	"database/sql"
)

type Command struct {
	ID         int64          `json:"id"`
	JobID      string         `json:"job_id"`
	Command    string         `json:"command"`
	FileOutput sql.NullString `json:"file_output"`
}

type Env struct {
	ID    int64  `json:"id"`
	JobID string `json:"job_id"`
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Job struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Cron string `json:"cron"`
}

type JobsView struct {
	ID   string     `json:"id"`
	Name string     `json:"name"`
	Cron string     `json:"cron"`
	Runs []RunsView `json:"runs"`
}

type Log struct {
	CreatedAt  int64  `json:"created_at"`
	RunID      int64  `json:"run_id"`
	SeverityID int64  `json:"severity_id"`
	Message    string `json:"message"`
}

type Run struct {
	ID        int64         `json:"id"`
	JobID     string        `json:"job_id"`
	StatusID  int64         `json:"status_id"`
	StartTime int64         `json:"start_time"`
	EndTime   sql.NullInt64 `json:"end_time"`
}

type RunsView struct {
	ID           int64                `json:"id"`
	JobID        string               `json:"job_id"`
	StatusID     int64                `json:"status_id"`
	StartTime    int64                `json:"start_time"`
	EndTime      sql.NullInt64        `json:"end_time"`
	FmtStartTime string               `json:"fmt_start_time"`
	FmtEndTime   sql.NullString       `json:"fmt_end_time"`
	Duration     sql.NullInt64        `json:"duration"`
	Logs         []ListLogsByRunIDRow `json:"logs"`
}

type Severity struct {
	ID       int64  `json:"id"`
	Severity string `json:"severity"`
}

type Status struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}
