// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: status.sql

package jobs

import (
	"context"
)

const createStatus = `-- name: CreateStatus :one
INSERT INTO
    status (status)
VALUES
    (?) RETURNING id, status
`

func (q *Queries) CreateStatus(ctx context.Context, status string) (Status, error) {
	row := q.db.QueryRowContext(ctx, createStatus, status)
	var i Status
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const listStatus = `-- name: ListStatus :many
SELECT
    id, status
FROM
    status
ORDER BY
    id
`

func (q *Queries) ListStatus(ctx context.Context) ([]Status, error) {
	rows, err := q.db.QueryContext(ctx, listStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Status
	for rows.Next() {
		var i Status
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
