// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetJobsData, GetJobsResponse, GetJobsError, PostJobsData, PostJobsResponse, PostJobsError, GetJobData, GetJobResponse, GetJobError, PostJobData, PostJobResponse, PostJobError, GetVersionsData, GetVersionsResponse, GetVersionsError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get jobs
 * Get jobs with run details but no logs.
 */
export const getJobs = <ThrowOnError extends boolean = false>(options?: Options<GetJobsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetJobsResponse, GetJobsError, ThrowOnError>({
        url: '/api/jobs',
        ...options
    });
};

/**
 * Start jobs
 * Start all jobs in order of name.
 */
export const postJobs = <ThrowOnError extends boolean = false>(options?: Options<PostJobsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostJobsResponse, PostJobsError, ThrowOnError>({
        url: '/api/jobs',
        ...options
    });
};

/**
 * Get job
 * Get job with run details and logs.
 */
export const getJob = <ThrowOnError extends boolean = false>(options: Options<GetJobData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetJobResponse, GetJobError, ThrowOnError>({
        url: '/api/jobs/{name}',
        ...options
    });
};

/**
 * Start job
 * Start single job.
 */
export const postJob = <ThrowOnError extends boolean = false>(options: Options<PostJobData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostJobResponse, PostJobError, ThrowOnError>({
        url: '/api/jobs/{name}',
        ...options
    });
};

/**
 * Get installed versions
 * Get installed versions of software.
 */
export const getVersions = <ThrowOnError extends boolean = false>(options?: Options<GetVersionsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetVersionsResponse, GetVersionsError, ThrowOnError>({
        url: '/api/versions',
        ...options
    });
};