// This file is auto-generated by @hey-api/openapi-ts

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type Information = {
    name: string;
    repo: string;
    version: string;
};

export type JobsView = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    cron: string;
    id: string;
    name: string;
    runs: Array<RunsView> | null;
};

export type ListLogsByRunIdRow = {
    created_at: number;
    created_at_time: unknown;
    message: string;
    run_id: number;
    severity_id: number;
};

export type NullInt64 = {
    Int64: number;
    Valid: boolean;
};

export type NullString = {
    String: string;
    Valid: boolean;
};

export type RunsView = {
    duration: NullInt64;
    end_time: NullInt64;
    fmt_end_time: NullString;
    fmt_start_time: string;
    id: number;
    job_id: string;
    logs: Array<ListLogsByRunIdRow> | null;
    start_time: number;
    status_id: number;
};

export type GetJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/jobs';
};

export type GetJobsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetJobsError = GetJobsErrors[keyof GetJobsErrors];

export type GetJobsResponses = {
    /**
     * OK
     */
    200: Array<JobsView> | null;
};

export type GetJobsResponse = GetJobsResponses[keyof GetJobsResponses];

export type PostJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/jobs';
};

export type PostJobsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostJobsError = PostJobsErrors[keyof PostJobsErrors];

export type PostJobsResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostJobsResponse = PostJobsResponses[keyof PostJobsResponses];

export type GetJobData = {
    body?: never;
    path: {
        /**
         * job name
         */
        name: string;
    };
    query?: {
        /**
         * number of runs to return
         */
        limit?: number;
    };
    url: '/api/jobs/{name}';
};

export type GetJobErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * OK
     */
    200: JobsView;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type PostJobData = {
    body?: never;
    path: {
        /**
         * job name
         */
        name: string;
    };
    query?: never;
    url: '/api/jobs/{name}';
};

export type PostJobErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostJobError = PostJobErrors[keyof PostJobErrors];

export type PostJobResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostJobResponse = PostJobResponses[keyof PostJobResponses];

export type GetVersionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/versions';
};

export type GetVersionsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetVersionsError = GetVersionsErrors[keyof GetVersionsErrors];

export type GetVersionsResponses = {
    /**
     * OK
     */
    200: Array<Information> | null;
};

export type GetVersionsResponse = GetVersionsResponses[keyof GetVersionsResponses];

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};